version: '3.5'

services:
  api:
    image: node:10-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:3000
    command: npm start
  redis:
    image: redis:5-alpine